name: Deploy selflove-member to Lolipop

on:
  push:
    branches:
      - main   # デフォルトブランチが master なら master に変更

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      # リポジトリの中身を取ってくる
        uses: actions/checkout@v4

      - name: Deploy via WebDAV
        uses: XPH0816/webdav-deploy-action@v0.3
        with:
          url: ${{ secrets.LOLIPOP_WEBDAV_URL }}
          username: ${{ secrets.LOLIPOP_WEBDAV_USER }}
          password: ${{ secrets.LOLIPOP_WEBDAV_PASS }}
          local: "./"
          remote: "/selflove/member"
